### ISSUE TITLE
Codecov file recognition

### ISSUE THREAD

**Issue by millzpaugh** [mapbox/mason-js#27]
codecov isn't recognizing all files in the `lib` folder. Investigate why this is happening!

**Comment by millzpaugh** [comment]
This is now working on master!!! 

![screen shot 2018-02-28 at 9 29 16 am](https://user-images.githubusercontent.com/4648295/36802504-eb5b950e-1c69-11e8-878b-257c3d4d7809.png)

**Comment by springmeyer** [comment]
awesome @millzpaugh!
