### ISSUE TITLE
Incompatibility issue with node 4.4.7

### ISSUE THREAD

**Issue by millzpaugh** [mapbox/mason-js#49]
@GretaCB hit an issue trying to compile node-cpp-skel with mason-js. This error appears to originate with the node v4.4.7 `Buffer` object. See https://stackoverflow.com/questions/36899888/getting-typeerror-this-is-not-a-typed-array-using-buffer-from-in-mocha

**Error output**
```
node_modules/.bin/mason-js install
info Mason Package Install Starting 
info check checked for protozero (not found locally)
info check checked for clang++ (not found locally)
info check checked for clang-tidy (not found locally)
info check checked for clang-format (not found locally)
info check checked for llvm-cov (not found locally)
info check checked for binutils (not found locally)
ERR! TypeError: this is not a typed array. 
make: *** [mason_packages/headers] Error 1
```

The error is being thrown at `awaitAll` https://github.com/mapbox/mason-js/blob/master/index.js#L40, it looks like it has something to do with piping the tar file. (Thanks for digging into this @GretaCB!)

@springmeyer how do you feel about this package supporting => node v4.8?

**Comment by springmeyer** [comment]
thanks for ticketing - great to have this for reference if we ever hit again. Because node v4.4.7 ~ 2 years old (https://nodejs.org/en/blog/release/v4.4.7/) I think I'm comfortable with this problem being solved by requiring >= node v4.8.x.
